from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from database import get_db
from auth import require_chin_auth, require_officer_integrity, TokenClaims
from modules.audit.schemas import AuditLogResponse
from modules.audit.service import AuditService
from modules.documents.service import DocumentsService

router = APIRouter()

@router.get("/citizen/{chin}", response_model=List[AuditLogResponse])
def get_citizen_audit_trail(
    chin: str, 
    db: Session = Depends(get_db),
    current_user: TokenClaims = Depends(require_chin_auth)
):
    """
    Returns the complete immutable audit trail for a citizen profile.
    """
    if current_user.sub != chin and current_user.role != "officer":
        raise HTTPException(status_code=403, detail="Unauthorized to access this audit trail")
        
    trail = AuditService.get_citizen_trail(db, chin)
    return trail

@router.get("/document/{doc_id}", response_model=List[AuditLogResponse])
def get_document_audit_trail(
    doc_id: str, 
    db: Session = Depends(get_db),
    current_user: TokenClaims = Depends(require_chin_auth)
):
    """
    Returns access and modification log history for a specific document.
    """
    doc = DocumentsService.get_document(db, doc_id)
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
        
    if doc.chin != current_user.sub and current_user.role != "officer":
        raise HTTPException(status_code=403, detail="Unauthorized to access this document's logs")
        
    trail = AuditService.get_document_trail(db, doc_id)
    return trail

@router.get("/institution/{inst_id}", response_model=List[AuditLogResponse])
def get_institution_audit_trail(
    inst_id: str, 
    db: Session = Depends(get_db),
    current_officer: TokenClaims = Depends(require_officer_integrity)
):
    """
    Returns activity logs generated by an institutional node. Gated by officer integrity.
    """
    trail = AuditService.get_institution_trail(db, inst_id)
    return trail

@router.get("/officer/{chin}", response_model=List[AuditLogResponse])
def get_officer_audit_trail(
    chin: str, 
    db: Session = Depends(get_db),
    current_officer: TokenClaims = Depends(require_officer_integrity)
):
    """
    Retrieves the complete action log of a government officer. Gated by officer integrity.
    """
    if current_officer.sub != chin and current_officer.role != "court":
        raise HTTPException(status_code=403, detail="Unauthorized to view this officer's logs")
        
    trail = AuditService.get_officer_trail(db, chin)
    return trail

@router.get("/tx/{blockchain_tx}", response_model=AuditLogResponse)
def lookup_audit_by_blockchain_tx(
    blockchain_tx: str, 
    db: Session = Depends(get_db),
    current_user: TokenClaims = Depends(require_chin_auth)
):
    """
    Fetches the audit database entry linked to a specific blockchain transaction ID.
    """
    log = AuditService.get_by_tx(db, blockchain_tx)
    if not log:
        raise HTTPException(status_code=404, detail="Audit log entry not found for this blockchain transaction")
    return log
